#!/bin/bash
#
# Lab Management System - 一键部署脚本
# 使用方法: curl -fsSL https://raw.githubusercontent.com/PatrickLiYunpeng/lab-management-system/main/deploy.sh | bash
#

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}"
echo "╔════════════════════════════════════════════════╗"
echo "║   Lab Management System - 一键部署脚本         ║"
echo "║   版本: v2.1                                   ║"
echo "╚════════════════════════════════════════════════╝"
echo -e "${NC}"

# 检查是否为 root 用户
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}请使用 root 用户运行此脚本${NC}"
    echo "命令: sudo bash deploy.sh"
    exit 1
fi

# 获取服务器公网IP
SERVER_IP=$(curl -s ifconfig.me || curl -s ip.sb || echo "localhost")
echo -e "${YELLOW}检测到服务器IP: ${SERVER_IP}${NC}"

# ========== 步骤1: 安装 Docker ==========
echo ""
echo -e "${GREEN}[1/6] 安装 Docker...${NC}"

if command -v docker &> /dev/null; then
    echo "Docker 已安装，跳过"
else
    apt-get update -qq
    apt-get install -y -qq curl wget git
    curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun
    systemctl start docker
    systemctl enable docker
    echo "Docker 安装完成"
fi

# 配置镜像加速
mkdir -p /etc/docker
cat > /etc/docker/daemon.json <<EOF
{
  "registry-mirrors": [
    "https://registry.cn-hangzhou.aliyuncs.com",
    "https://mirror.ccs.tencentyun.com"
  ]
}
EOF
systemctl daemon-reload
systemctl restart docker

# ========== 步骤2: 克隆项目 ==========
echo ""
echo -e "${GREEN}[2/6] 下载项目代码...${NC}"

cd /opt
if [ -d "lab-management-system" ]; then
    echo "项目目录已存在，更新代码..."
    cd lab-management-system
    git pull origin main
else
    git clone https://github.com/PatrickLiYunpeng/lab-management-system.git
    cd lab-management-system
fi

# ========== 步骤3: 配置环境变量 ==========
echo ""
echo -e "${GREEN}[3/6] 配置环境变量...${NC}"

# 生成随机密码和密钥
MYSQL_ROOT_PASS=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
MYSQL_USER_PASS=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
SECRET_KEY=$(openssl rand -hex 32)

cat > .env <<EOF
# Auto-generated by deploy.sh at $(date)
SERVER_IP=${SERVER_IP}

# MySQL Configuration
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
MYSQL_DATABASE=lab_management
MYSQL_USER=lab_user
MYSQL_PASSWORD=${MYSQL_USER_PASS}

# Backend Configuration
SECRET_KEY=${SECRET_KEY}
ACCESS_TOKEN_EXPIRE_MINUTES=1440
DEBUG=false
EOF

echo "环境变量配置完成"

# ========== 步骤4: 构建前端 ==========
echo ""
echo -e "${GREEN}[4/6] 构建前端...${NC}"

if [ -d "frontend/dist" ] && [ -f "frontend/dist/index.html" ]; then
    echo "前端已构建，跳过"
else
    echo "安装 Node.js..."
    if ! command -v node &> /dev/null; then
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y -qq nodejs
    fi
    cd frontend
    npm install --legacy-peer-deps
    npm run build
    cd ..
    echo "前端构建完成"
fi

# ========== 步骤5: 启动 Docker 服务 ==========
echo ""
echo -e "${GREEN}[5/6] 启动 Docker 服务...${NC}"

# 停止旧容器（如果存在）
docker compose down 2>/dev/null || true

# 启动服务
docker compose up -d --build

# 等待服务启动
echo "等待服务启动..."
sleep 30

# ========== 步骤6: 验证部署 ==========
echo ""
echo -e "${GREEN}[6/6] 验证部署...${NC}"

# 检查容器状态
if docker compose ps | grep -q "Up"; then
    echo -e "${GREEN}所有服务已启动${NC}"
else
    echo -e "${RED}部分服务启动失败，请检查日志:${NC}"
    docker compose logs --tail=50
    exit 1
fi

# 测试前端
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/ 2>/dev/null || echo "000")
if [ "$HTTP_CODE" = "200" ]; then
    echo -e "${GREEN}前端服务正常 (HTTP $HTTP_CODE)${NC}"
else
    echo -e "${YELLOW}前端服务可能还在启动中 (HTTP $HTTP_CODE)${NC}"
fi

# 测试后端
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/api/v1/auth/login -X POST -H "Content-Type: application/json" -d '{}' 2>/dev/null || echo "000")
if [ "$HTTP_CODE" = "422" ]; then
    echo -e "${GREEN}后端API正常 (HTTP $HTTP_CODE)${NC}"
else
    echo -e "${YELLOW}后端API可能还在启动中 (HTTP $HTTP_CODE)${NC}"
fi

# ========== 完成 ==========
echo ""
echo -e "${GREEN}"
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                    部署完成！                              ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║                                                            ║"
echo "║  访问地址: http://${SERVER_IP}                            "
echo "║                                                            ║"
echo "║  默认账号: admin                                           ║"
echo "║  默认密码: admin123                                        ║"
echo "║                                                            ║"
echo "║  ⚠️  请立即修改默认密码！                                   ║"
echo "║                                                            ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║  数据库信息（已保存到 /opt/lab-management-system/.env）    ║"
echo "║  MySQL Root 密码: ${MYSQL_ROOT_PASS}                       "
echo "║  MySQL User 密码: ${MYSQL_USER_PASS}                       "
echo "╚════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo ""
echo "常用命令:"
echo "  查看状态: cd /opt/lab-management-system && docker compose ps"
echo "  查看日志: cd /opt/lab-management-system && docker compose logs -f"
echo "  重启服务: cd /opt/lab-management-system && docker compose restart"
echo ""
