"""add_product_management_tables

Revision ID: c935eac5de3a
Revises: 94da6500f185
Create Date: 2026-02-04 21:49:01.500277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c935eac5de3a'
down_revision: Union[str, None] = '94da6500f185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='应用场景名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='应用场景代码'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='显示顺序'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述说明'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='UI显示颜色'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认选项'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_application_scenarios_code'), 'application_scenarios', ['code'], unique=True)
    op.create_index(op.f('ix_application_scenarios_id'), 'application_scenarios', ['id'], unique=False)
    op.create_table('package_form_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='封装形式名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='封装形式代码'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='显示顺序'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述说明'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认选项'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_package_form_options_code'), 'package_form_options', ['code'], unique=True)
    op.create_index(op.f('ix_package_form_options_id'), 'package_form_options', ['id'], unique=False)
    op.create_table('package_type_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='封装类型名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='封装类型代码'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='显示顺序'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述说明'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认选项'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_package_type_options_code'), 'package_type_options', ['code'], unique=True)
    op.create_index(op.f('ix_package_type_options_id'), 'package_type_options', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='产品名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='产品代码'),
    sa.Column('client_id', sa.Integer(), nullable=False, comment='所属客户ID'),
    sa.Column('package_form_id', sa.Integer(), nullable=True, comment='封装形式ID'),
    sa.Column('package_type_id', sa.Integer(), nullable=True, comment='封装类型ID'),
    sa.Column('custom_info', sa.JSON(), nullable=True, comment='自定义产品信息，JSON数组格式[{key, value}]'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['package_form_id'], ['package_form_options.id'], ),
    sa.ForeignKeyConstraint(['package_type_id'], ['package_type_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_client_id'), 'products', ['client_id'], unique=False)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('product_application_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='产品ID'),
    sa.Column('scenario_id', sa.Integer(), nullable=False, comment='应用场景ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['application_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_application_scenarios_id'), 'product_application_scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_product_application_scenarios_product_id'), 'product_application_scenarios', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_application_scenarios_scenario_id'), 'product_application_scenarios', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_application_scenarios_scenario_id'), table_name='product_application_scenarios')
    op.drop_index(op.f('ix_product_application_scenarios_product_id'), table_name='product_application_scenarios')
    op.drop_index(op.f('ix_product_application_scenarios_id'), table_name='product_application_scenarios')
    op.drop_table('product_application_scenarios')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_index(op.f('ix_products_client_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_package_type_options_id'), table_name='package_type_options')
    op.drop_index(op.f('ix_package_type_options_code'), table_name='package_type_options')
    op.drop_table('package_type_options')
    op.drop_index(op.f('ix_package_form_options_id'), table_name='package_form_options')
    op.drop_index(op.f('ix_package_form_options_code'), table_name='package_form_options')
    op.drop_table('package_form_options')
    op.drop_index(op.f('ix_application_scenarios_id'), table_name='application_scenarios')
    op.drop_index(op.f('ix_application_scenarios_code'), table_name='application_scenarios')
    op.drop_table('application_scenarios')
    # ### end Alembic commands ###
