"""add_client_sla_and_testing_source_categories

Revision ID: 0f40818a482a
Revises: e0ac3c607be0
Create Date: 2026-02-01 11:00:42.698436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f40818a482a'
down_revision: Union[str, None] = 'e0ac3c607be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing_source_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('priority_weight', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_testing_source_categories_id'), 'testing_source_categories', ['id'], unique=False)
    op.create_index(op.f('ix_testing_source_categories_name'), 'testing_source_categories', ['name'], unique=False)
    op.create_table('client_slas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('commitment_hours', sa.Integer(), nullable=False),
    sa.Column('max_hours', sa.Integer(), nullable=True),
    sa.Column('priority_weight', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_slas_id'), 'client_slas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_slas_id'), table_name='client_slas')
    op.drop_table('client_slas')
    op.drop_index(op.f('ix_testing_source_categories_name'), table_name='testing_source_categories')
    op.drop_index(op.f('ix_testing_source_categories_id'), table_name='testing_source_categories')
    op.drop_table('testing_source_categories')
    # ### end Alembic commands ###
