"""split service_type into method_type and source_category_id

Revision ID: 1f11967eb327
Revises: a1b2c3d4e5f6
Create Date: 2026-02-04 22:35:11.208290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f11967eb327'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_slas', sa.Column('method_type', sa.Enum('ANALYSIS', 'RELIABILITY', name='methodtype'), nullable=True))
    op.add_column('client_slas', sa.Column('source_category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_client_slas_method_type'), 'client_slas', ['method_type'], unique=False)
    op.create_foreign_key(None, 'client_slas', 'testing_source_categories', ['source_category_id'], ['id'])
    op.drop_column('client_slas', 'service_type')
    op.alter_column('material_replenishments', 'received_date',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='收货日期',
               existing_nullable=False)
    op.alter_column('material_replenishments', 'quantity_added',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='增加数量',
               existing_nullable=False)
    op.alter_column('material_replenishments', 'sap_order_no',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='SAP订单号',
               existing_nullable=True)
    op.alter_column('material_replenishments', 'non_sap_source',
               existing_type=mysql.ENUM('internal_transfer', 'emergency_purchase', 'gift_sample', 'inventory_adjustment', 'other', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='非SAP来源',
               existing_nullable=True)
    op.alter_column('material_replenishments', 'notes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('material_replenishments', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('material_replenishments', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('material_replenishments', 'notes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='备注',
               existing_nullable=True)
    op.alter_column('material_replenishments', 'non_sap_source',
               existing_type=mysql.ENUM('internal_transfer', 'emergency_purchase', 'gift_sample', 'inventory_adjustment', 'other', collation='utf8mb4_unicode_ci'),
               comment='非SAP来源',
               existing_nullable=True)
    op.alter_column('material_replenishments', 'sap_order_no',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='SAP订单号',
               existing_nullable=True)
    op.alter_column('material_replenishments', 'quantity_added',
               existing_type=mysql.INTEGER(),
               comment='增加数量',
               existing_nullable=False)
    op.alter_column('material_replenishments', 'received_date',
               existing_type=mysql.DATETIME(),
               comment='收货日期',
               existing_nullable=False)
    op.add_column('client_slas', sa.Column('service_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.drop_constraint(None, 'client_slas', type_='foreignkey')
    op.drop_index(op.f('ix_client_slas_method_type'), table_name='client_slas')
    op.drop_column('client_slas', 'source_category_id')
    op.drop_column('client_slas', 'method_type')
    # ### end Alembic commands ###
