"""add_required_capacity_to_tasks

Revision ID: 94da6500f185
Revises: 4d9bbb753808
Create Date: 2026-02-01 14:21:19.125379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94da6500f185'
down_revision: Union[str, None] = '4d9bbb753808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order_tasks', sa.Column('required_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order_tasks', 'required_capacity')
    # ### end Alembic commands ###
