"""initial_schema

Revision ID: 0dc77fe68afa
Revises: 
Create Date: 2026-01-31 22:58:18.651950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc77fe68afa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('default_sla_days', sa.Integer(), nullable=True),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('source_category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_code'), 'clients', ['code'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_code'), 'sites', ['code'], unique=True)
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('category', sa.Enum('EQUIPMENT_OPERATION', 'TESTING_METHOD', 'ANALYSIS_TECHNIQUE', 'SOFTWARE_TOOL', 'SAFETY_PROCEDURE', 'OTHER', name='skillcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_certification', sa.Boolean(), nullable=True),
    sa.Column('certification_validity_days', sa.Integer(), nullable=True),
    sa.Column('lab_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_code'), 'skills', ['code'], unique=True)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('standard_cycle_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_category', sa.String(length=100), nullable=False),
    sa.Column('work_order_type', sa.Enum('FAILURE_ANALYSIS', 'RELIABILITY_TEST', name='workordertype'), nullable=False),
    sa.Column('lab_type', sa.String(length=20), nullable=True),
    sa.Column('equipment_type', sa.String(length=50), nullable=True),
    sa.Column('standard_hours', sa.Float(), nullable=False),
    sa.Column('min_hours', sa.Float(), nullable=True),
    sa.Column('max_hours', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_cycle_times_id'), 'standard_cycle_times', ['id'], unique=False)
    op.create_index(op.f('ix_standard_cycle_times_task_category'), 'standard_cycle_times', ['task_category'], unique=False)
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('lab_type', sa.Enum('FA', 'RELIABILITY', name='laboratorytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('manager_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratories_code'), 'laboratories', ['code'], unique=True)
    op.create_index(op.f('ix_laboratories_id'), 'laboratories', ['id'], unique=False)
    op.create_index(op.f('ix_laboratories_lab_type'), 'laboratories', ['lab_type'], unique=False)
    op.create_index(op.f('ix_laboratories_name'), 'laboratories', ['name'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('equipment_type', sa.Enum('AUTONOMOUS', 'OPERATOR_DEPENDENT', name='equipmenttype'), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('uph', sa.Float(), nullable=True),
    sa.Column('max_concurrent_tasks', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'MAINTENANCE', 'OUT_OF_SERVICE', 'RESERVED', name='equipmentstatus'), nullable=False),
    sa.Column('last_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('next_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('maintenance_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_calibration_date', sa.DateTime(), nullable=True),
    sa.Column('next_calibration_date', sa.DateTime(), nullable=True),
    sa.Column('calibration_interval_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('warranty_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_code'), 'equipment', ['code'], unique=True)
    op.create_index(op.f('ix_equipment_equipment_type'), 'equipment', ['equipment_type'], unique=False)
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'ENGINEER', 'TECHNICIAN', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('primary_laboratory_id', sa.Integer(), nullable=True),
    sa.Column('primary_site_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['primary_laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['primary_site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('equipment_skill_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('min_proficiency_level', sa.String(length=20), nullable=True),
    sa.Column('requires_certification', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_skill_requirements_id'), 'equipment_skill_requirements', ['id'], unique=False)
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('primary_laboratory_id', sa.Integer(), nullable=False),
    sa.Column('primary_site_id', sa.Integer(), nullable=False),
    sa.Column('current_laboratory_id', sa.Integer(), nullable=True),
    sa.Column('current_site_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'BUSY', 'ON_LEAVE', 'BORROWED', name='personnelstatus'), nullable=False),
    sa.Column('hire_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['current_site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['primary_laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['primary_site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_personnel_employee_id'), 'personnel', ['employee_id'], unique=True)
    op.create_index(op.f('ix_personnel_id'), 'personnel', ['id'], unique=False)
    op.create_table('personnel_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiencylevel'), nullable=False),
    sa.Column('is_certified', sa.Boolean(), nullable=True),
    sa.Column('certification_date', sa.Date(), nullable=True),
    sa.Column('certification_expiry', sa.Date(), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('last_assessment_date', sa.Date(), nullable=True),
    sa.Column('assessment_score', sa.Integer(), nullable=True),
    sa.Column('assessed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personnel_skills_id'), 'personnel_skills', ['id'], unique=False)
    op.create_table('staff_borrow_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('from_laboratory_id', sa.Integer(), nullable=False),
    sa.Column('to_laboratory_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_laboratory_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_borrow_requests_id'), 'staff_borrow_requests', ['id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_order_type', sa.Enum('FAILURE_ANALYSIS', 'RELIABILITY_TEST', name='workordertype'), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('testing_source', sa.String(length=50), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('assigned_engineer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'REVIEW', 'COMPLETED', 'CANCELLED', name='workorderstatus'), nullable=False),
    sa.Column('standard_cycle_hours', sa.Float(), nullable=True),
    sa.Column('actual_cycle_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_engineer_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_order_number'), 'work_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_work_order_type'), 'work_orders', ['work_order_type'], unique=False)
    op.create_table('work_order_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('task_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('assigned_technician_id', sa.Integer(), nullable=True),
    sa.Column('required_equipment_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_equipment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('standard_cycle_hours', sa.Float(), nullable=True),
    sa.Column('actual_cycle_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['required_equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['scheduled_equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_tasks_id'), 'work_order_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_work_order_tasks_status'), 'work_order_tasks', ['status'], unique=False)
    op.create_table('equipment_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['work_order_tasks.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_schedules_end_time'), 'equipment_schedules', ['end_time'], unique=False)
    op.create_index(op.f('ix_equipment_schedules_id'), 'equipment_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_schedules_start_time'), 'equipment_schedules', ['start_time'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('material_type', sa.Enum('SAMPLE', 'CONSUMABLE', 'REAGENT', 'TOOL', 'OTHER', name='materialtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_reference', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'IN_STORAGE', 'ALLOCATED', 'IN_USE', 'PENDING_RETURN', 'RETURNED', 'DISPOSED', 'LOST', name='materialstatus'), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('storage_deadline', sa.DateTime(), nullable=True),
    sa.Column('processing_deadline', sa.DateTime(), nullable=True),
    sa.Column('current_work_order_id', sa.Integer(), nullable=True),
    sa.Column('current_task_id', sa.Integer(), nullable=True),
    sa.Column('current_equipment_id', sa.Integer(), nullable=True),
    sa.Column('disposal_method', sa.Enum('RETURN_TO_CLIENT', 'ARCHIVE', 'RECYCLE', 'HAZARDOUS_DISPOSAL', 'STANDARD_DISPOSAL', name='disposalmethod'), nullable=True),
    sa.Column('disposed_at', sa.DateTime(), nullable=True),
    sa.Column('disposed_by_id', sa.Integer(), nullable=True),
    sa.Column('disposal_notes', sa.Text(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('return_tracking_number', sa.String(length=100), nullable=True),
    sa.Column('return_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['current_equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['current_task_id'], ['work_order_tasks.id'], ),
    sa.ForeignKeyConstraint(['current_work_order_id'], ['work_orders.id'], ),
    sa.ForeignKeyConstraint(['disposed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_material_code'), 'materials', ['material_code'], unique=True)
    op.create_index(op.f('ix_materials_material_type'), 'materials', ['material_type'], unique=False)
    op.create_index(op.f('ix_materials_name'), 'materials', ['name'], unique=False)
    op.create_index(op.f('ix_materials_status'), 'materials', ['status'], unique=False)
    op.create_table('material_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('RECEIVED', 'IN_STORAGE', 'ALLOCATED', 'IN_USE', 'PENDING_RETURN', 'RETURNED', 'DISPOSED', 'LOST', name='materialstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('RECEIVED', 'IN_STORAGE', 'ALLOCATED', 'IN_USE', 'PENDING_RETURN', 'RETURNED', 'DISPOSED', 'LOST', name='materialstatus'), nullable=False),
    sa.Column('from_location', sa.String(length=100), nullable=True),
    sa.Column('to_location', sa.String(length=100), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['work_order_tasks.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_history_id'), 'material_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_history_id'), table_name='material_history')
    op.drop_table('material_history')
    op.drop_index(op.f('ix_materials_status'), table_name='materials')
    op.drop_index(op.f('ix_materials_name'), table_name='materials')
    op.drop_index(op.f('ix_materials_material_type'), table_name='materials')
    op.drop_index(op.f('ix_materials_material_code'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_equipment_schedules_start_time'), table_name='equipment_schedules')
    op.drop_index(op.f('ix_equipment_schedules_id'), table_name='equipment_schedules')
    op.drop_index(op.f('ix_equipment_schedules_end_time'), table_name='equipment_schedules')
    op.drop_table('equipment_schedules')
    op.drop_index(op.f('ix_work_order_tasks_status'), table_name='work_order_tasks')
    op.drop_index(op.f('ix_work_order_tasks_id'), table_name='work_order_tasks')
    op.drop_table('work_order_tasks')
    op.drop_index(op.f('ix_work_orders_work_order_type'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_order_number'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_staff_borrow_requests_id'), table_name='staff_borrow_requests')
    op.drop_table('staff_borrow_requests')
    op.drop_index(op.f('ix_personnel_skills_id'), table_name='personnel_skills')
    op.drop_table('personnel_skills')
    op.drop_index(op.f('ix_personnel_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_employee_id'), table_name='personnel')
    op.drop_table('personnel')
    op.drop_index(op.f('ix_equipment_skill_requirements_id'), table_name='equipment_skill_requirements')
    op.drop_table('equipment_skill_requirements')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_type'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_code'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_laboratories_name'), table_name='laboratories')
    op.drop_index(op.f('ix_laboratories_lab_type'), table_name='laboratories')
    op.drop_index(op.f('ix_laboratories_id'), table_name='laboratories')
    op.drop_index(op.f('ix_laboratories_code'), table_name='laboratories')
    op.drop_table('laboratories')
    op.drop_index(op.f('ix_standard_cycle_times_task_category'), table_name='standard_cycle_times')
    op.drop_index(op.f('ix_standard_cycle_times_id'), table_name='standard_cycle_times')
    op.drop_table('standard_cycle_times')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_code'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_code'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_code'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
