"""add_methods_tables

Revision ID: ca15b07af86c
Revises: 0dc77fe68afa
Create Date: 2026-02-01 04:01:21.998407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca15b07af86c'
down_revision: Union[str, None] = '0dc77fe68afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_code'), 'shifts', ['code'], unique=True)
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_table('methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('method_type', sa.Enum('ANALYSIS', 'RELIABILITY', name='methodtype'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('procedure_summary', sa.Text(), nullable=True),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('standard_cycle_hours', sa.Float(), nullable=True),
    sa.Column('min_cycle_hours', sa.Float(), nullable=True),
    sa.Column('max_cycle_hours', sa.Float(), nullable=True),
    sa.Column('requires_equipment', sa.Boolean(), nullable=True),
    sa.Column('default_equipment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methods_code'), 'methods', ['code'], unique=True)
    op.create_index(op.f('ix_methods_id'), 'methods', ['id'], unique=False)
    op.create_index(op.f('ix_methods_method_type'), 'methods', ['method_type'], unique=False)
    op.create_index(op.f('ix_methods_name'), 'methods', ['name'], unique=False)
    op.create_table('method_skill_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('min_proficiency_level', sa.String(length=20), nullable=True),
    sa.Column('requires_certification', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_method_skill_requirements_id'), 'method_skill_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_method_skill_requirements_method_id'), 'method_skill_requirements', ['method_id'], unique=False)
    op.create_index(op.f('ix_method_skill_requirements_skill_id'), 'method_skill_requirements', ['skill_id'], unique=False)
    op.create_table('personnel_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_personnel_shift_dates', 'personnel_shifts', ['personnel_id', 'effective_date'], unique=False)
    op.create_index(op.f('ix_personnel_shifts_effective_date'), 'personnel_shifts', ['effective_date'], unique=False)
    op.create_index(op.f('ix_personnel_shifts_id'), 'personnel_shifts', ['id'], unique=False)
    op.create_table('task_handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('from_technician_id', sa.Integer(), nullable=False),
    sa.Column('to_technician_id', sa.Integer(), nullable=True),
    sa.Column('from_shift_id', sa.Integer(), nullable=True),
    sa.Column('to_shift_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'cancelled', name='handoverstatus'), nullable=False),
    sa.Column('priority', sa.Enum('normal', 'urgent', 'critical', name='handoverpriority'), nullable=False),
    sa.Column('task_status_at_handover', sa.String(length=50), nullable=True),
    sa.Column('progress_summary', sa.Text(), nullable=True),
    sa.Column('pending_items', sa.Text(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('acceptance_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['from_technician_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['work_order_tasks.id'], ),
    sa.ForeignKeyConstraint(['to_shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['to_technician_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_handovers_from_technician_id'), 'task_handovers', ['from_technician_id'], unique=False)
    op.create_index(op.f('ix_task_handovers_id'), 'task_handovers', ['id'], unique=False)
    op.create_index(op.f('ix_task_handovers_task_id'), 'task_handovers', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_handovers_to_technician_id'), 'task_handovers', ['to_technician_id'], unique=False)
    op.create_index(op.f('ix_task_handovers_work_order_id'), 'task_handovers', ['work_order_id'], unique=False)
    op.create_table('handover_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handover_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['handover_id'], ['task_handovers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handover_notes_handover_id'), 'handover_notes', ['handover_id'], unique=False)
    op.create_index(op.f('ix_handover_notes_id'), 'handover_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handover_notes_id'), table_name='handover_notes')
    op.drop_index(op.f('ix_handover_notes_handover_id'), table_name='handover_notes')
    op.drop_table('handover_notes')
    op.drop_index(op.f('ix_task_handovers_work_order_id'), table_name='task_handovers')
    op.drop_index(op.f('ix_task_handovers_to_technician_id'), table_name='task_handovers')
    op.drop_index(op.f('ix_task_handovers_task_id'), table_name='task_handovers')
    op.drop_index(op.f('ix_task_handovers_id'), table_name='task_handovers')
    op.drop_index(op.f('ix_task_handovers_from_technician_id'), table_name='task_handovers')
    op.drop_table('task_handovers')
    op.drop_index(op.f('ix_personnel_shifts_id'), table_name='personnel_shifts')
    op.drop_index(op.f('ix_personnel_shifts_effective_date'), table_name='personnel_shifts')
    op.drop_index('ix_personnel_shift_dates', table_name='personnel_shifts')
    op.drop_table('personnel_shifts')
    op.drop_index(op.f('ix_method_skill_requirements_skill_id'), table_name='method_skill_requirements')
    op.drop_index(op.f('ix_method_skill_requirements_method_id'), table_name='method_skill_requirements')
    op.drop_index(op.f('ix_method_skill_requirements_id'), table_name='method_skill_requirements')
    op.drop_table('method_skill_requirements')
    op.drop_index(op.f('ix_methods_name'), table_name='methods')
    op.drop_index(op.f('ix_methods_method_type'), table_name='methods')
    op.drop_index(op.f('ix_methods_id'), table_name='methods')
    op.drop_index(op.f('ix_methods_code'), table_name='methods')
    op.drop_table('methods')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_code'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
