"""equipment_names add is_critical remove display_order

Revision ID: aab1a5b414bd
Revises: e5f6g7h8i9j0
Create Date: 2026-02-05 02:41:51.194441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aab1a5b414bd'
down_revision: Union[str, None] = 'e5f6g7h8i9j0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_names', sa.Column('is_critical', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.drop_column('equipment_names', 'display_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_names', sa.Column('display_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.drop_column('equipment_names', 'is_critical')
    # ### end Alembic commands ###
